# Step 1: add name
name: CI workflow

# Step 2: add event triggers
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# Step 3: add a Job
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout Step
      - name: Checkout
        uses: actions/checkout@v3 # The "actions/checkout" action is commonly used at the beginning of workflows to clone your repository's source code into the runner's workspace. This step ensures that the latest version of your code is available for subsequent steps in the job.
      # Install Dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
      # Lint with flake8
      - name: Lint with flake8
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics
      # Test Code Coverage with nosetests
      - name: Run unit tests with nose
        run: nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
    # Step 4: target Python 3.9
    container: python:3.9-slim